#!/usr/bin/env bash

set -u

abort() {
  printf "%s\n" "$@" >&2
  exit 1
}

shell_join() {
    local arg
    printf "%s" "$1"
    shift
    for arg in "$@"; do
        printf " "
        printf "%s" "${arg// /\ }"
    done
}

execute() {
    if ! "$@"; then
        abort "$(printf "Failed during: %s" "$(shell_join "$@")")"
    fi
}

# Fail fast with a concise message when not using bash
# Single brackets are needed here for POSIX compatibility
if [ -z "${BASH_VERSION:-}" ]; then
    abort "Bash is required to interpret this script."
fi

if ! command -v git > /dev/null; then
    abort "Git is required before install this script."
fi

cd ~
BASHRC_REPO=~/.bashrc.git
if [ -d .bashrc.git ]; then
    builtin pushd $BASHRC_REPO
    execute "git" "fetch" "--force" "origin"
    execute "git" "fetch" "--force" "--tags" "origin"

    execute "git" "reset" "--hard" "origin/main"
    builtin popd
else
    execute "git" "clone" "https://github.com/bingzhangdai/bashrc.git" $BASHRC_REPO
fi

append_line() {
    set -e

    local line="$1"
    local file="$2"
    local pat="${3:-}"
    local lno=""

    echo "Update $file:"
    echo "  - $line"
    if [ -f "$file" ]; then
        if [ $# -lt 3 ]; then
            lno=$(\grep -nF "$line" "$file" | sed 's/:.*//' | tr '\n' ' ')
        else
            lno=$(\grep -nF "$pat" "$file" | sed 's/:.*//' | tr '\n' ' ')
        fi
    fi
    if [ -n "$lno" ]; then
        echo "    - Already exists: line #$lno"
    else
        [ -f "$file" ] && echo >> "$file"
        echo "$line" >> "$file"
        echo "    + Added"
    fi
    echo

    set +e
}

append_line "source $BASHRC_REPO/bash_logout" ~/.bash_logout
append_line "\$include $BASHRC_REPO/inputrc" ~/.inputrc

if ! command -v envsubst > /dev/null; then
    abort "envsubst is required before install this script."
fi

(
    set -a
    source $BASHRC_REPO/scripts/settings.default.bash
    [[ -r "~/.settings.bash" ]] && source "~/.settings.bash"
    set +a
    mv ~/.settings.bash ~/.settings.bash.$(date "+%Y%m%d-%s%3N")
    cat "$BASHRC_REPO/scripts/settings.tpl.bash" | envsubst > ~/.settings.bash
)

append_line 'source ~/.settings.bash' ~/.bashrc
append_line "source $BASHRC_REPO/bashrc" ~/.bashrc

# TOD: install packages